// Lista de temas
const temas = [
    "Experiencia 1: Aductor muñeca, Corazón, Corte atriocapsular, Art. atlantoaxoidea, Portocava",
    "Experiencia 2: PVN pierna, Músculos eversores, Corazón, Corte retrocalloso, Inervación MI",
    "Experiencia 3: Fosa del codo, Estómago, Corte atrioventricular, Drenaje venoso MI",
    "Experiencia 4: Art. glenohumeral, Peritoneo, Vía corticoespinal",
    "Experiencia 5: Cráneo, Vías biliares, Corte antero-genículo, Mano, Vías extrapiramidales",
    "Experiencia 6: Triángulo femoral, PVN cuello, Corte anterocapsular, Bóveda plantar",
    "Experiencia 7: Glenohumeral, Segmentación broncopulmonar, Corte anterocapsular, Fosa isquioanal",
    "Experiencia 8: Nervio mediano, Mesentéricas, Faringe, Corte retrolenticular, Axila, Porta",
    "Experiencia 9: Cráneo, Mediastino, Corte atrioventricular, Techo nasal, Pulmón derecho",
    "Experiencia 10: Pie, Mediastino, Corte astaoccipital, Vía biliar, Tráquea",
    "Experiencia 11: Rodilla, Pie, Hígado, Corte retrolenticular, Irrigación médula",
    "Experiencia 12: Cadera, Riñones, Biomecánica hombro, Pares craneales parasimpáticos",
    "Experiencia 13: Triángulo femoral, Páncreas, Fascias periné, Complejo amigdalino",
    "Experiencia 14: Fosa axilar, Hígado, Corte del atrio, Fosa poplítea, Celda prostática",
    "Experiencia 15: Triángulo femoral, Corazón, Corte geniculocapsular, Retroperitoneo",
    "Experiencia 16: Rodilla, Riñón, Corte posterocapsular, Fosa pterigopalatina, Vía visual",
    "Experiencia 17: Clavícula, Hígado, Fórceps mayor, Tabaquera anatómica, Hipogloso",
    "Experiencia 18: Escápula, Hemicara, Corte posterocapsular",
    "Experiencia 19: Antebrazo, Axis, Riñones, Tráquea, Inervación mano, Rodilla",
    "Experiencia 20: Húmero, Antebrazo, Intestinos, PVN cuello, Corte posterocapsular, Conducto inguinal",
    "Experiencia 21: Glenohumeral, Cuello, Corte posterocapsular, Espacio laterofaríngeo",
    "Experiencia 22: Hombro, Órganos tórax, Corte anterocapsular/precalloso, Inervación pie, Irrigación corazón",
    "Experiencia 23: Rodilla, Mediastino, Forámenes cráneo, Triángulo Budde, Reflejo fotomotor",
    "Experiencia 24: Bóveda plantar, Corte faringe, Plexo braquial, Circuitos cerebelosos",
    "Experiencia 25: Rodilla, Riñón, Cráneo, Nervio mediano, Estómago, Caja timpánica",
    "Experiencia 26: Pierna y rodilla, Laríngeos recurrentes, Corte atrio, Caja timpánica",
    "Experiencia 27: Pierna y fémur, Segmentación broncopulmonar, Fosa pterigopalatina, Periné",
    "Experiencia 28: Fosa poplítea, Corazón, Faringe, Vías piramidales",
    "Experiencia 29: Músculos pie, Mediastino, Afluentes VCI, Complejo articular hombro",
    "Experiencia 30: PVN pierna/pie, Corazón (Koch/Dominancia), Corte posterocapsular, Articulaciones pie",
    "Experiencia 31: Plexo braquial, Rodilla, Ilíaca interna, Conducto inguinal, Fosa isquioanal",
    "Experiencia 32: Glenohumeral, Cuello, Corte geniculocapsular, Espacio perifaríngeo",
    "Experiencia 33: Triángulo femoral, Corazón, Corte geniculocapsular, Rodilla, Bazo",
    "Experiencia 34: Rodilla, Hemicara, Corte posterocapsular, Conducto inguinal, Seno maxilar",
    "Experiencia 35: Rodilla, Plexo braquial, Cuello, Uretra masculina, Portocava",
    "Experiencia 36: Fosa axilar, Corazón, Endobase, Dominancia cardíaca",
    "Experiencia 37: Axila, Faringe, Corte atrioventricular, Articulación talocrural, Reflejo fotomotor",
    "Experiencia 38: Pierna, Riñón, Corte retrolenticular, Mediastino posterior, Reflejo corneal",
    "Experiencia 39: Hombro, Hígado, Corte del atrio, Inervación mano, Hiato Winslow",
    "Experiencia 40: Vértebras, Canal del pulso, Corte precalloso, Oído interno",
    "Experiencia 41: Triángulo femoral, Pie, Antebrazo, Drenaje venoso bazo",
    "Experiencia 42: Vértebra, Art. atlantoaxial, Cuello, Sisarcosis, Sistema cardionector",
    "Experiencia 43: Endobase, Hemipelvis, Inervación mano, Medios fijación útero",
    "Experiencia 44: Húmero, Vía biliar, Corte atrio, Triángulo femoral, Oído medio",
    "Experiencia 45: Pierna/Poplítea, Cara, Corte geniculo y antero, Fórmula dentaria, Núcleos vestibulares",
    "Experiencia 46: Fosa poplítea, Endofaringe, Endocráneo, Colédoco, Vena porta",
    "Experiencia 47: Dorso/Nuca, Carpo, Hígado, Sistema cardionector, Vía columna dorsal",
    "Experiencia 48: Glenohumeral, Corazón, Corte del atrio, Diafragma, Vías corticonuclear",
    "Experiencia 49: Rodilla, Hígado, Corte anterocapsular, Sistema cardionector, Irrigación encéfalo",
    "Experiencia 50: Antebrazo, Faringe, Corte anterocapsular, Laringe, Periné",
    "Experiencia 51: Antebrazo, Arterias mesentéricas, Corte retrocalloso, Plexo braquial, Ovario",
    "Experiencia 52: Escápula, Vías extrahepáticas, Corte posterocapsular, Inervación palma mano",
    "Experiencia 53: Endobase, Bazo, Corte atrio, Biomecánica codo, Estómago, Hipocampo",
    "Experiencia 54: Pierna posterior, Laringe, Vías extrahepáticas, Corte retrocalloso, Fosa poplítea",
    "Experiencia 55: Espacios axilares, Endobase, Biomecánica dedos, Irrigación estómago, Caja timpánica",
    "Experiencia 56: Surco bicipital, Pelvis, Corte retrocalloso, Sistema cardionector, 4to ventrículo",
    "Experiencia 57: Hígado y faringe, Corte postero y retrolenticular, Próstata, Duodeno",
    "Experiencia 58: Atlas y axis, Glenohumeral, Laringe, Fosa poplítea, Cerebelo",
    "Experiencia 59: Tendones antebrazo, Segmentación broncopulmonar, Corte posterocapsular, Hiato Winslow",
    "Experiencia 60: Axis y atlantooccipital, Laringe, Intestino",
    "Experiencia 61: Antebrazo, Nodo sinusal, Corte atrioventricular, Segmentación hepática, Tráquea",
    "Experiencia 62: Coxal, Axila, Hemipelvis, Corazón, Corte geniculo/postero, Vía corticoespinal",
    "Experiencia 63: Clavícula, Retroperitoneo, Corte anterocapsular, Nervio oculomotor, Conducto inguinal",
    "Experiencia 64: Triángulo femoral, Corazón, Cráneo, Reflejo fotomotor, Articulación talocrural",
    "Experiencia 65: Corte anterocapsular, Art. glenohumeral, Laringe, Tiroides, Rodilla",
    "Experiencia 66: Laringe, Escápula, Corte posterocapsular, Hipófisis, Estómago, Pie",
    "Experiencia 67: Coxofemoral, Riñones, Corte de Jakob, Talocrural, Reflejos, Próstata",
    "Experiencia 68: Triángulo femoral, Corazón, Endobase, Vía visual, Miosis, Porta",
    "Experiencia 69: Riñón, Art. glenohumeral, Duodeno/páncreas, Vía visual, Colon",
    "Experiencia 70: Corte parietooccipital, Vías extrapiramidales",
    "Experiencia 71: Corte retrocalloso, Hombro, Cuello/Tráquea, Rodilla, Estómago",
    "Experiencia 72: Cuello, Antebrazo, Corte postero/retro, Próstata, Órbita",
    "Experiencia 73: Fosa craneal media, Corte geniculocapsular, Vías biliares, PVN cuello, Cuerpo calloso, Tiroides",
    "Experiencia 74: Corte antero y postero, Vasos cuello, Arterias pelvis, Triángulo femoral, Epitálamo, Riñón",
    "Rodilla (Biomecánica y Ligamentos)",
    "Corazón (Configuración y Cardionector)",
    "Cortes del Encéfalo (Jacob y Flechsig)",
    "Mediastino y Tórax",
    "Hígado (Segmentación y Relaciones)",
    "Laringe (Configuración e Inervación)",
    "Nervio Mediano y Plexo Braquial)",
    "Segmentación Broncopulmonar",
    "Tráquea (Cervical y Torácica)",
    "Triángulo Femoral",
    "Bóveda Plantar",
    "Fosa Poplítea",
    "Vías Biliares y Triángulo de Budde",
    "Estómago (Relaciones e Irrigación)",
    "Inervación Sensitiva (Mano, Pie, MI)",
    "Faringe (Límites y Comunicaciones)",
    "Riñón y Retroperitoneo",
    "Articulación de la Cadera (Coxofemoral)",
    "Espacio Perifaríngeo y Fosa Pterigopalatina",
    "Caja Timpánica y Oído Medio",
    "Articulación Glenohumeral",
    "Plexos Coroideos y Ventrículos",
    "Irrigación (Estómago, Corazón, Encéfalo)",
    "Vía Visual, Auditiva y Reflejo Fotomotor",
    "PVN (Cuello, Mediastino, Pierna)",
    "Fosa Axilar",
    "Carótidas y Ramas",
    "Diafragma (Hiatos e Inserciones)",
    "Linfáticos (Pulmón, Mama, MI)",
    "Mesentéricas y Aorta Abdominal"
];

// Função para mostrar um tema aleatório
function mostrarTemaAleatorio() {
    const temaAleatorio = temas[Math.floor(Math.random() * temas.length)];
    document.getElementById("tema").textContent = temaAleatorio;
}

// Chama a função na carga inicial da página
window.onload = mostrarTemaAleatorio;




